//
//  Generated by preggers 0.2.0.
//

#import <Foundation/Foundation.h>


@class Compiler;


@protocol EvenParserDataSource;
typedef NSObject<EvenParserDataSource> EvenParserDataSource;

typedef struct { int begin, end;  SEL action; } yythunk;

@interface EvenParser : NSObject
{
    EvenParserDataSource *_dataSource;
    NSString *_string;
    NSUInteger _index;
    NSUInteger _limit;
    NSString *_text;

    int	yybegin;
    int	yyend;
    yythunk *yythunks;
    int	yythunkslen;
    int yythunkpos;

    Compiler *_compiler;
}

@property (retain) EvenParserDataSource *dataSource;
@property (retain) Compiler *compiler;

- (BOOL) parse;
- (BOOL) parseString:(NSString *)string;

@end


@protocol EvenParserDataSource

- (NSString *) nextString;

@end

