//
//  Generated by preggers 0.3.0.
//

#import <Foundation/Foundation.h>




@protocol EvenParserDataSource;
typedef NSObject<EvenParserDataSource> EvenParserDataSource;

typedef struct { int begin, end;  SEL action; } yythunk;

@interface EvenParser : NSObject
{
    EvenParserDataSource *_dataSource;
    NSString *_string;
    NSUInteger _index;
    NSUInteger _limit;
    NSString *_text;

    int	yybegin;
    int	yyend;
    yythunk *yythunks;
    int	yythunkslen;
    int yythunkpos;

}

@property (retain) EvenParserDataSource *dataSource;

- (BOOL) parse;
- (BOOL) parseString:(NSString *)string;

@end


@protocol EvenParserDataSource

- (NSString *) nextString;

@end

