
@option case-insensitive

Equation <- Primary EndOfFile

Primary <- Secondary ( PLUS  Secondary { [self.compiler add]; }
                     / MINUS Secondary { [self.compiler subtract]; }
                     )*

Secondary <- Tertiary ( MUL Tertiary { [self.compiler multiply]; }
                      / DIV Tertiary { [self.compiler divide];   }
                      )*

Tertiary <- Terminal EXP Tertiary { [self.compiler exponent]; }
          / (PLUS / MINUS { [self.compiler negative]; })+ Tertiary
          / Terminal

Terminal <- OPEN Primary CLOSE
          / "pow" OPEN Primary COMMA Primary CLOSE { [self.compiler exponent]; }
          / Number { [self.compiler pushNumber:text]; }

Number <- < [0-9+] > _

OPEN      <- '(' _
CLOSE     <- ')' _
COMMA     <- ',' _

EXP       <- '**' _
MUL       <- '*' _
DIV       <- '/' _
PLUS      <- '+' _
MINUS     <- '-' _
_         <- ' '*
EndOfFile <- !.
