//
//  Generated by preggers 0.3.0.
//

#import <Foundation/Foundation.h>


@class Calculator;


@protocol CalcParserDataSource;
typedef NSObject<CalcParserDataSource> CalcParserDataSource;

typedef struct { int begin, end;  SEL action; } yythunk;

@interface CalcParser : NSObject
{
    CalcParserDataSource *_dataSource;
    NSString *_string;
    NSUInteger _index;
    NSUInteger _limit;
    NSString *_text;

    int	yybegin;
    int	yyend;
    yythunk *yythunks;
    int	yythunkslen;
    int yythunkpos;

    Calculator *_calculator;
}

@property (retain) CalcParserDataSource *dataSource;
@property (retain) Calculator *calculator;

- (BOOL) parse;
- (BOOL) parseString:(NSString *)string;

@end


@protocol CalcParserDataSource

- (NSString *) nextString;

@end

