//
//  Generated by preggers 0.2.0.
//

#import "CalcParser.h"

#import "Compiler.h"

@interface CalcParser ()

- (BOOL) _matchDot;
- (BOOL) _matchString:(char *)s;
- (BOOL) _matchClass:(unsigned char *)bits;
#define CALCPARSER_CASE_INSENSITIVE
- (BOOL) matchCLOSE;
- (BOOL) matchCOMMA;
- (BOOL) matchDIV;
- (BOOL) matchEXP;
- (BOOL) matchEndOfFile;
- (BOOL) matchEquation;
- (BOOL) matchMINUS;
- (BOOL) matchMUL;
- (BOOL) matchNumber;
- (BOOL) matchOPEN;
- (BOOL) matchPLUS;
- (BOOL) matchPrimary;
- (BOOL) matchSecondary;
- (BOOL) matchTerminal;
- (BOOL) matchTertiary;
- (BOOL) match_;

@end


@implementation CalcParser

@synthesize dataSource = _dataSource;
@synthesize compiler = _compiler;

//==================================================================================================
#pragma mark -
#pragma mark Rules
//==================================================================================================


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 32

#ifdef matchDEBUG
#define yyprintf(args)	{ fprintf args; fprintf(stderr," @ %s\n",[[_string substringFromIndex:_index] UTF8String]); }
#else
#define yyprintf(args)
#endif

- (BOOL) _refill
{
    if (!self.dataSource)
        return NO;

    NSString *nextString = [self.dataSource nextString];
    if (nextString)
    {
        nextString = [_string stringByAppendingString:nextString];
        [_string release];
        _string = [nextString retain];
    }
    _limit = [_string lengthOfBytesUsingEncoding:NSUTF8StringEncoding];
    yyprintf((stderr, "refill"));
    return YES;
}

- (BOOL) _matchDot
{
    if (_index >= _limit && ![self _refill]) return NO;
    ++_index;
    return YES;
}

- (BOOL) _matchString:(char *)s
{
#ifndef CALCPARSER_CASE_INSENSITIVE
    const char *cstring = [_string UTF8String];
#else
    const char *cstring = [[_string lowercaseString] UTF8String];
#endif
    int saved = _index;
    while (*s)
    {
        if (_index >= _limit && ![self _refill]) return NO;
        if (cstring[_index] != *s)
        {
            _index = saved;
    yyprintf((stderr, "  fail _matchString"));
            return NO;
        }
        ++s;
        ++_index;
    }
    yyprintf((stderr, "  ok   _matchString"));
    return YES;
}

- (BOOL) _matchClass:(unsigned char *)bits
{
    if (_index >= _limit && ![self _refill]) return NO;
    int c = [_string characterAtIndex:_index];
    if (bits[c >> 3] & (1 << (c & 7)))
    {
        ++_index;
        yyprintf((stderr, "  ok   _matchClass"));
        return YES;
    }
    yyprintf((stderr, "  fail _matchClass"));
    return NO;
}

- (void) yyDo:(SEL)action
{
    while (yythunkpos >= yythunkslen)
    {
        yythunkslen *= 2;
        yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
    yythunks[yythunkpos].begin=  yybegin;
    yythunks[yythunkpos].end=    yyend;
    yythunks[yythunkpos].action= action;
    ++yythunkpos;
}

- (void) yyText:(int)begin to:(int)end
{
    int len = end - begin;
    if (len <= 0)
    {
        [_text release];
        _text = nil;
    }
    else
    {
        _text = [_string substringWithRange:NSMakeRange(begin, end-begin)];
        [_text retain];
    }
}

- (void) yyDone
{
    int pos;
    for (pos= 0;  pos < yythunkpos;  ++pos)
    {
        yythunk *thunk= &yythunks[pos];
        [self yyText:thunk->begin to:thunk->end];
        yyprintf((stderr, "DO [%d] %s %s\n", pos, [NSStringFromSelector(thunk->action) UTF8String], [_text UTF8String]));
        [self performSelector:thunk->action withObject:_text];
    }
    yythunkpos= 0;
}

- (void) yyCommit
{
    NSString *newString = [_string substringFromIndex:_index];
    [_string release];
    _string = [newString retain];
    _limit -= _index;
    _index = 0;

    yybegin -= _index;
    yyend -= _index;
    yythunkpos= 0;
}

- (void) yy_1_Primary:(NSString *)text
{
 [self.compiler add]; ;
}

- (void) yy_2_Primary:(NSString *)text
{
 [self.compiler subtract]; ;
}

- (void) yy_1_Secondary:(NSString *)text
{
 [self.compiler multiply]; ;
}

- (void) yy_2_Secondary:(NSString *)text
{
 [self.compiler divide];   ;
}

- (void) yy_1_Tertiary:(NSString *)text
{
 [self.compiler exponent]; ;
}

- (void) yy_2_Tertiary:(NSString *)text
{
 [self.compiler negative]; ;
}

- (void) yy_1_Terminal:(NSString *)text
{
 [self.compiler exponent]; ;
}

- (void) yy_2_Terminal:(NSString *)text
{
 [self.compiler pushNumber:text]; ;
}

- (BOOL) matchCLOSE
{
    NSUInteger index0=_index, yythunkpos1=yythunkpos;
    yyprintf((stderr, "%s", "CLOSE"));
    if (![self _matchString:")"]) goto L2;
    if (![self match_]) goto L2;
    yyprintf((stderr, "  ok   %s", "CLOSE"));
    return YES;
L2:
    _index=index0; yythunkpos=yythunkpos1;
    yyprintf((stderr, "  fail %s", "CLOSE"));
    return NO;
}

- (BOOL) matchCOMMA
{
    NSUInteger index5=_index, yythunkpos6=yythunkpos;
    yyprintf((stderr, "%s", "COMMA"));
    if (![self _matchString:","]) goto L7;
    if (![self match_]) goto L7;
    yyprintf((stderr, "  ok   %s", "COMMA"));
    return YES;
L7:
    _index=index5; yythunkpos=yythunkpos6;
    yyprintf((stderr, "  fail %s", "COMMA"));
    return NO;
}

- (BOOL) matchDIV
{
    NSUInteger index10=_index, yythunkpos11=yythunkpos;
    yyprintf((stderr, "%s", "DIV"));
    if (![self _matchString:"/"]) goto L12;
    if (![self match_]) goto L12;
    yyprintf((stderr, "  ok   %s", "DIV"));
    return YES;
L12:
    _index=index10; yythunkpos=yythunkpos11;
    yyprintf((stderr, "  fail %s", "DIV"));
    return NO;
}

- (BOOL) matchEXP
{
    NSUInteger index15=_index, yythunkpos16=yythunkpos;
    yyprintf((stderr, "%s", "EXP"));
    if (![self _matchString:"**"]) goto L17;
    if (![self match_]) goto L17;
    yyprintf((stderr, "  ok   %s", "EXP"));
    return YES;
L17:
    _index=index15; yythunkpos=yythunkpos16;
    yyprintf((stderr, "  fail %s", "EXP"));
    return NO;
}

- (BOOL) matchEndOfFile
{
    NSUInteger index20=_index, yythunkpos21=yythunkpos;
    yyprintf((stderr, "%s", "EndOfFile"));
    NSUInteger index23=_index, yythunkpos24=yythunkpos;
    if ([self _matchDot]) goto L22;
    _index=index23; yythunkpos=yythunkpos24;
    yyprintf((stderr, "  ok   %s", "EndOfFile"));
    return YES;
L22:
    _index=index20; yythunkpos=yythunkpos21;
    yyprintf((stderr, "  fail %s", "EndOfFile"));
    return NO;
}

- (BOOL) matchEquation
{
    NSUInteger index25=_index, yythunkpos26=yythunkpos;
    yyprintf((stderr, "%s", "Equation"));
    if (![self matchPrimary]) goto L27;
    if (![self matchEndOfFile]) goto L27;
    yyprintf((stderr, "  ok   %s", "Equation"));
    return YES;
L27:
    _index=index25; yythunkpos=yythunkpos26;
    yyprintf((stderr, "  fail %s", "Equation"));
    return NO;
}

- (BOOL) matchMINUS
{
    NSUInteger index30=_index, yythunkpos31=yythunkpos;
    yyprintf((stderr, "%s", "MINUS"));
    if (![self _matchString:"-"]) goto L32;
    if (![self match_]) goto L32;
    yyprintf((stderr, "  ok   %s", "MINUS"));
    return YES;
L32:
    _index=index30; yythunkpos=yythunkpos31;
    yyprintf((stderr, "  fail %s", "MINUS"));
    return NO;
}

- (BOOL) matchMUL
{
    NSUInteger index35=_index, yythunkpos36=yythunkpos;
    yyprintf((stderr, "%s", "MUL"));
    if (![self _matchString:"*"]) goto L37;
    if (![self match_]) goto L37;
    yyprintf((stderr, "  ok   %s", "MUL"));
    return YES;
L37:
    _index=index35; yythunkpos=yythunkpos36;
    yyprintf((stderr, "  fail %s", "MUL"));
    return NO;
}

- (BOOL) matchNumber
{
    NSUInteger index40=_index, yythunkpos41=yythunkpos;
    yyprintf((stderr, "%s", "Number"));
    yybegin = _index;
    if (![self _matchClass:(unsigned char *)"\000\000\000\000\000\010\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"]) goto L42;
    yyend = _index;
    if (![self match_]) goto L42;
    yyprintf((stderr, "  ok   %s", "Number"));
    return YES;
L42:
    _index=index40; yythunkpos=yythunkpos41;
    yyprintf((stderr, "  fail %s", "Number"));
    return NO;
}

- (BOOL) matchOPEN
{
    NSUInteger index45=_index, yythunkpos46=yythunkpos;
    yyprintf((stderr, "%s", "OPEN"));
    if (![self _matchString:"("]) goto L47;
    if (![self match_]) goto L47;
    yyprintf((stderr, "  ok   %s", "OPEN"));
    return YES;
L47:
    _index=index45; yythunkpos=yythunkpos46;
    yyprintf((stderr, "  fail %s", "OPEN"));
    return NO;
}

- (BOOL) matchPLUS
{
    NSUInteger index50=_index, yythunkpos51=yythunkpos;
    yyprintf((stderr, "%s", "PLUS"));
    if (![self _matchString:"+"]) goto L52;
    if (![self match_]) goto L52;
    yyprintf((stderr, "  ok   %s", "PLUS"));
    return YES;
L52:
    _index=index50; yythunkpos=yythunkpos51;
    yyprintf((stderr, "  fail %s", "PLUS"));
    return NO;
}

- (BOOL) matchPrimary
{
    NSUInteger index55=_index, yythunkpos56=yythunkpos;
    yyprintf((stderr, "%s", "Primary"));
    if (![self matchSecondary]) goto L57;
    ;
    NSUInteger index60, yythunkpos61;
L62:
    index60=_index; yythunkpos61=yythunkpos;
    NSUInteger index64=_index, yythunkpos65=yythunkpos;
    if (![self matchPLUS]) goto L67;
    if (![self matchSecondary]) goto L67;
    [self yyDo:@selector(yy_1_Primary:)];
    goto L66;
L67:
    _index=index64; yythunkpos=yythunkpos65;
    if (![self matchMINUS]) goto L63;
    if (![self matchSecondary]) goto L63;
    [self yyDo:@selector(yy_2_Primary:)];
    goto L66;
L66:
    goto L62;
L63:
    _index=index60; yythunkpos=yythunkpos61;
    yyprintf((stderr, "  ok   %s", "Primary"));
    return YES;
L57:
    _index=index55; yythunkpos=yythunkpos56;
    yyprintf((stderr, "  fail %s", "Primary"));
    return NO;
}

- (BOOL) matchSecondary
{
    NSUInteger index72=_index, yythunkpos73=yythunkpos;
    yyprintf((stderr, "%s", "Secondary"));
    if (![self matchTertiary]) goto L74;
    ;
    NSUInteger index77, yythunkpos78;
L79:
    index77=_index; yythunkpos78=yythunkpos;
    NSUInteger index81=_index, yythunkpos82=yythunkpos;
    if (![self matchMUL]) goto L84;
    if (![self matchTertiary]) goto L84;
    [self yyDo:@selector(yy_1_Secondary:)];
    goto L83;
L84:
    _index=index81; yythunkpos=yythunkpos82;
    if (![self matchDIV]) goto L80;
    if (![self matchTertiary]) goto L80;
    [self yyDo:@selector(yy_2_Secondary:)];
    goto L83;
L83:
    goto L79;
L80:
    _index=index77; yythunkpos=yythunkpos78;
    yyprintf((stderr, "  ok   %s", "Secondary"));
    return YES;
L74:
    _index=index72; yythunkpos=yythunkpos73;
    yyprintf((stderr, "  fail %s", "Secondary"));
    return NO;
}

- (BOOL) matchTerminal
{
    NSUInteger index89=_index, yythunkpos90=yythunkpos;
    yyprintf((stderr, "%s", "Terminal"));
    NSUInteger index92=_index, yythunkpos93=yythunkpos;
    if (![self matchOPEN]) goto L95;
    if (![self matchPrimary]) goto L95;
    if (![self matchCLOSE]) goto L95;
    goto L94;
L95:
    _index=index92; yythunkpos=yythunkpos93;
    if (![self _matchString:"pow"]) goto L98;
    if (![self matchOPEN]) goto L98;
    if (![self matchPrimary]) goto L98;
    if (![self matchCOMMA]) goto L98;
    if (![self matchPrimary]) goto L98;
    if (![self matchCLOSE]) goto L98;
    [self yyDo:@selector(yy_1_Terminal:)];
    goto L94;
L98:
    _index=index92; yythunkpos=yythunkpos93;
    if (![self matchNumber]) goto L91;
    [self yyDo:@selector(yy_2_Terminal:)];
    goto L94;
L94:
    yyprintf((stderr, "  ok   %s", "Terminal"));
    return YES;
L91:
    _index=index89; yythunkpos=yythunkpos90;
    yyprintf((stderr, "  fail %s", "Terminal"));
    return NO;
}

- (BOOL) matchTertiary
{
    NSUInteger index103=_index, yythunkpos104=yythunkpos;
    yyprintf((stderr, "%s", "Tertiary"));
    NSUInteger index106=_index, yythunkpos107=yythunkpos;
    if (![self matchTerminal]) goto L109;
    if (![self matchEXP]) goto L109;
    if (![self matchTertiary]) goto L109;
    [self yyDo:@selector(yy_1_Tertiary:)];
    goto L108;
L109:
    _index=index106; yythunkpos=yythunkpos107;
    NSUInteger index117=_index, yythunkpos118=yythunkpos;
    if (![self matchPLUS]) goto L120;
    goto L119;
L120:
    _index=index117; yythunkpos=yythunkpos118;
    if (![self matchMINUS]) goto L112;
    [self yyDo:@selector(yy_2_Tertiary:)];
    goto L119;
L119:
    ;
    NSUInteger index115, yythunkpos116;
L123:
    index115=_index; yythunkpos116=yythunkpos;
    NSUInteger index125=_index, yythunkpos126=yythunkpos;
    if (![self matchPLUS]) goto L128;
    goto L127;
L128:
    _index=index125; yythunkpos=yythunkpos126;
    if (![self matchMINUS]) goto L124;
    [self yyDo:@selector(yy_2_Tertiary:)];
    goto L127;
L127:
    goto L123;
L124:
    _index=index115; yythunkpos=yythunkpos116;
    if (![self matchTertiary]) goto L112;
    goto L108;
L112:
    _index=index106; yythunkpos=yythunkpos107;
    if (![self matchTerminal]) goto L105;
    goto L108;
L108:
    yyprintf((stderr, "  ok   %s", "Tertiary"));
    return YES;
L105:
    _index=index103; yythunkpos=yythunkpos104;
    yyprintf((stderr, "  fail %s", "Tertiary"));
    return NO;
}

- (BOOL) match_
{
    NSUInteger index131=_index, yythunkpos132=yythunkpos;
    yyprintf((stderr, "%s", "_"));
    ;
    NSUInteger index134, yythunkpos135;
L136:
    index134=_index; yythunkpos135=yythunkpos;
    if (![self _matchString:" "]) goto L137;
    goto L136;
L137:
    _index=index134; yythunkpos=yythunkpos135;
    yyprintf((stderr, "  ok   %s", "_"));
    return YES;
L133:
    _index=index131; yythunkpos=yythunkpos132;
    yyprintf((stderr, "  fail %s", "_"));
    return NO;
}

- (BOOL) yyparsefrom:(SEL)startRule
{
    BOOL yyok;
    if (!yythunkslen)
    {
        yythunkslen= 32;
        yythunks= malloc(sizeof(yythunk) * yythunkslen);
        yybegin= yyend= yythunkpos= 0;
    }
    if (!_string)
    {
        _string = [NSString new];
        _limit = 0;
        _index = 0;
    }
    yybegin= yyend= _index;
    yythunkpos= 0;

    NSMethodSignature *sig = [[self class] instanceMethodSignatureForSelector:startRule];
    NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:sig];
    [invocation setTarget:self];
    [invocation setSelector:startRule];
    [invocation invoke];
    [invocation getReturnValue:&yyok];
    if (yyok) [self yyDone];
    [self yyCommit];

    [_string release];
    _string = nil;
    [_text release];
    _text = nil;

    return yyok;
}

- (BOOL) yyparse
{
    return [self yyparsefrom:@selector(matchEquation)];
}


//==================================================================================================
#pragma mark -
#pragma mark NSObject Methods
//==================================================================================================

- (void) dealloc
{
    free(yythunks);

    [_string release];

    [super dealloc];
}


//==================================================================================================
#pragma mark -
#pragma mark Public Methods
//==================================================================================================

- (BOOL) parse
{
    NSAssert(_dataSource != nil, @"can't call -parse without specifying a data source");
    return [self yyparse];
}


- (BOOL) parseString:(NSString *)string
{
    _string = [string copy];
    _limit  = [_string lengthOfBytesUsingEncoding:NSUTF8StringEncoding];
    _index  = 0;
    BOOL retval = [self yyparse];
    [_string release];
    _string = nil;
    return retval;
}


@end

